x86/boot: don't rely on DCE to kill accept_memory
Without DCE enabled (for example when building with -O0), accept_memory
causes a linker failure:
/usr/bin/ld: arch/x86/boot/compressed/misc.o: in function `extract_kernel':
misc.c:(.text+0x5275): undefined reference to `accept_memory'
/usr/bin/ld: arch/x86/boot/compressed/vmlinux: hidden symbol `accept_memory' isn't defined
/usr/bin/ld: final link failed: bad value

This can be resolved by lumping it into the same stubbing as
init_unaccepted_memory.